apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  labels:
    app: dnsutils
spec:
  containers:
  - image: de.icr.io/k8straining/dnsutils:latest
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
