apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dep
  labels:
    app: myapp
    tier: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        tier: frontend
      name: myapp-pod
    spec:
      containers:
      - image: nginx:1.25
        name: nginx-container
