apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: acedeployment
  name: acedeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acedeployment
  strategy: {}
  
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acedeployment
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 1001
      containers:
      - image: de.icr.io/k8straining/ace-cont:latest
        imagePullPolicy: Always
        name: ace-cont
        resources: {}
        volumeMounts:
        - mountPath: "/Data"
          name: data-volume
        securityContext:
          allowPrivilegeEscalation: false
      volumes: 
      - name: data-volume
        persistentVolumeClaim:
          claimName: pvc-data          
status: {}
