apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
spec:
  storageClassName: custom-file-bronze-gid
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Mi
