apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
  labels:
    kubernetes.io/cluster-service: "true"
  name: custom-file-bronze-gid
parameters:
  billingType: hourly
  classVersion: "2"
  gidAllocate: "true"
  gidFixed: "1001"
  iopsPerGB: "2"
  sizeRange: '[20-12000]Gi'
  type: Endurance
provisioner: ibm.io/ibmc-file
reclaimPolicy: Retain
volumeBindingMode: Immediate
